---
- name: Apt Upgrade Hosts
  hosts: all
  serial: "{{ serial_hosts | default(4) }}"
  max_fail_percentage: 25
  tasks:
    - name: "Send Slack notification"
      slack:
        token: "{{ slack_token }}"
        msg: K3s cluster system event
        attachments:
          - text: Initiating apt dist upgrade of k3s cluster nodes
            color: warning
            title: System packages upgrade
      delegate_to: localhost
      run_once: yes

    - name: Update apt-cache
      apt:
        update_cache: yes
      become: yes

    - name: Run apt dist-upgrade
      apt:
        upgrade: dist
        autoclean: yes
      become: yes
      register: output

    - name: Show apt dist-upgrade results
      debug:
        msg: "{{ output.stdout_lines }}"

    # Only reboot the host if the reboot_enabled var is set to true
    - name: Reboot host
      command: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      become: yes
      ignore_errors: true
      when:
        - reboot_enabled | default(false) | bool

    - name: "Wait for host to boot up"
      wait_for:
        host: "{{ ansible_host }}"
        search_regex: OpenSSH
        port: 22
        delay: 1
        timeout: 300
      connection: local
      when:
        - reboot_enabled | default(false) | bool

    - name: Check host uptime
      command: uptime
      register: output

    - name: Show host uptime
      debug:
        msg: "{{ output.stdout_lines }}"

    # Clean old packages from hosts
    - name: Remove un-used packages
      apt:
        autoremove: yes
      become: yes
      register: output

    - name: Show package cleaning results
      debug:
        msg: "{{ output.stdout_lines }}"
