---
- hosts: all
  vars:
    namespace: example
    deployments:
      - name: example-deployment
        app: example
        replicas: 2
        volumes:
          - name: html-volume
            configMap:
              name: mysite-html
        containers:
          - name: nginx
            image: nginx
            ports:
              - containerPort: 80
            volumeMounts:
              - name: html-volume
                mountPath: /usr/share/nginx/html
    services:
      - name: example-service
        app: example
        type: NodePort
        ports:
          - protocol: TCP
            port: 80
    ingress_configs:
      - name: example-ingress
        rules:
          - http:
              paths:
                - path: /
                  backend:
                    serviceName: example-service
                    servicePort: 80
  roles:
    - role: roles/k3s-deployment
